Partly ported spot to new filter architecture

diff --git a/packaging/scripts/photivo-release-package b/packaging/scripts/photivo-release-package
--- a/packaging/scripts/photivo-release-package
+++ b/packaging/scripts/photivo-release-package
@@ -1,36 +1,39 @@
 #!/bin/bash
 
-# number of threads for make's -j option
-MAKE_THREADS=4
+#============================= Start user config ===============================
+
+### Do not use spaces in any of the paths! ###
 
 # Qmake, Mercurial and Inno Setup compiler commands
-QMAKECMD=qmake
-HGCMD=hg
-ISSCMD=/c/bin32/InnoSetup/ISCC
+QmakeCmd=qmake
+MakeCmd=make
+HgCmd=hg
+IsscCmd=/c/bin32/InnoSetup/ISCC
 
-# Zip program for creating the troubleshooter. If you do not use 7-Zip you should
-# take a look at the actual command line below, might need changes.
-ZIPCMD=/c/bin32/7-Zip/7z
+# Zip program for creating the troubleshooter. 7-zip strongly recommended.
+# Must accept a command line of the form:
+# $ZipCmd output.zip inputfile1 inputfile2 inputfile3 ...
+ZipCmd="/c/bin32/7-Zip/7z a"
 
-# Path where the finished setup.exes should go during the cleanup stage
-ARCHIVEDIR=/d/Software/Anwendungen/Photivo
+# Software archive on the local hard disk.
+# Path (Msys notation) where the finished installers go during the cleanup stage.
+ArchivePath=/d/Software/Anwendungen/Photivo
 
-# Real location of /photivo. We could read this from fstab. But since it’s unlikely
-# to change too soon/often, setting it here is enough. Use forward slashes.
-REALBASEDIR="D:/Projekte/Photivo"
+# Location of the Photivo base folder as Msys and native path. Use forward slashes!
+MsysBasePath=/C/Projekte/Photivo
+RealBasePath=C:/Projekte/Photivo
 
-# Additional C++ compiler flags. Temporary solution until the C++11 stuff is properly
-# integrated into the Photivo project.
-MORECXXFLAGS="--std=gnu++0x -fpermissive"
+# Additional C++ compiler flags.
+MORECXXFLAGS=""
 
-#===============================================================================
+#============================= End user config =================================
 
-SCRIPTVERSION=1.0
-COLOR_RED='\e[1;31m'
-COLOR_GREEN='\e[0;32m'
-COLOR_NONE='\e[00m'
+ScriptVersion=1.0
+ColorRed='\e[1;31m'
+ColorGreen='\e[0;32m'
+ColorNone='\e[00m'
 
-SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+ScriptPath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 export CXXFLAGS="$CXXFLAGS $MORECXXFLAGS"
 
 #===============================================================================
@@ -38,8 +41,8 @@ export CXXFLAGS="$CXXFLAGS $MORECXXFLAGS"
 AbortOrNot() {
   read -n 1 -p "$1 (y/n)" PT_CONT
   if [ $PT_CONT = y ] || [ $PT_CONT = Y ]; then
-    echo ""
-    PT_CONT=
+    printf "\n"
+    unset PT_CONT
   else
     exit 1
   fi
@@ -47,21 +50,21 @@ AbortOrNot() {
 
 FileYesNo() {
   if [ -s "$1" ]; then
-    echo -e "${COLOR_GREEN}Yes${COLOR_NONE}"
+    echo -e "${ColorGreen}Yes${ColorNone}"
   else
-    echo -e "${COLOR_RED}No${COLOR_NONE}"
+    echo -e "${ColorRed}No${ColorNone}"
   fi
 }
 
 Error() {
-  echo -e "${COLOR_RED}$1${COLOR_NONE}"
+  echo -e "${ColorRed}$1${ColorNone}"
 }
 
 Cleanup() {
   echo -e "\nMoving setups ..."
   cp $PKGDIR/photivo-setup-${RELEASEDATE}-win64.exe \
      $PKGDIR/photivo-setup-${RELEASEDATE}-win32.exe \
-     $ARCHIVEDIR
+     $ArchivePath
   if [ ! $? -eq 0 ]; then
     Error "Copying setups failed. Aborting cleanup."
     echo "To clean up delete \"build-win-installer*\" folders manually."
@@ -69,12 +72,12 @@ Cleanup() {
   fi
 
   echo "Deleting temporary stuff ..."
-  rm -rf $PT_REPO_PATH/build-win-installer-64 && \
-  rm -rf $PT_REPO_PATH/build-win-installer-32 && \
+  rm -rf $PhotivoRepoPath/build-win-installer-64 && \
+  rm -rf $PhotivoRepoPath/build-win-installer-32 && \
   rm -rf $TSHOOTDIR && \
   rm -rf $PKGDIR
   if [ $? -eq 0 ]; then
-    echo -e "${COLOR_GREEN}All done.${COLOR_NONE}"
+    echo -e "${ColorGreen}All done.${ColorNone}"
     exit 0
   else
     Error "Cleanup failed."
@@ -85,35 +88,41 @@ Cleanup() {
 
 #===============================================================================
 
-echo "Create Photivo for Windows release package v$SCRIPTVERSION"
+echo ""
+echo "Create Photivo for Windows release package v$ScriptVersion"
 echo "---------------------------------------------------------------------------"
 
-if [ "$PT_REPO_PATH" = "" ]; then echo "PT_REPO_PATH not set!" ; exit 1 ; fi
-if [ "$PT_BINDIR" = "" ]; then echo "PT_BINDIR not set!" ; exit 1 ; fi
-if [ "$PT_BIT" != "64" ] && [ "$PT_BIT" != "32" ]; then echo "Wrong PT_BIT (${PT_BIT})!" ; exit 1 ; fi
+if [[ ("$PhotivoRepoPath" == "") || ("$PhotivoBuildPath" == "") ]]; then 
+  printf "No repo set. Cannot continue."
+  exit 1
+fi
+if [[ ("$GccArch" != "64") && ("$GccArch" != "32") ]]; then
+  echo "Wrong GccArch (${GccArch})!"
+  exit 1
+fi
 
-cd $PT_REPO_PATH
-HGBRANCH=$($HGCMD branch)
+cd $PhotivoRepoPath
+HGBRANCH=$($HgCmd branch)
 if [ ! "$HGBRANCH" = "default" ]; then
   echo -e "\nWorking copy is set to branch \"${HGBRANCH}\" instead of \"default\"."
   AbortOrNot "Continue anyway?"
 fi
 
-$HGCMD summary|grep "commit: (clean)" > /dev/null
+$HgCmd summary|grep "commit: (clean)" > /dev/null
 if [ ! $? -eq 0 ]; then
   echo -e "\nWorking copy has uncommitted changes."
   AbortOrNot "Continue anyway?"
 fi
 
-RELEASEDATE=$( $HGCMD log -b ${HGBRANCH} -l 1 --style ${SCRIPTDIR}/hg-shortdate.style )
+RELEASEDATE=$( $HgCmd log -b ${HGBRANCH} -l 1 --style ${ScriptPath}/hg-shortdate.style )
 
 #===============================================================================
 
 # Prepare folders
-BUILDDIR=$PT_REPO_PATH/build-win-installer-$PT_BIT
+BUILDDIR=$PhotivoRepoPath/build-win-installer-$GccArch
 BINDIR=$BUILDDIR/bin
-TSHOOTDIR=$PT_REPO_PATH/build-win-installer-tshoot
-PKGDIR=$PT_REPO_PATH/build-win-installer-pkg
+TSHOOTDIR=$PhotivoRepoPath/build-win-installer-tshoot
+PKGDIR=$PhotivoRepoPath/build-win-installer-pkg
 
 if [ -d $BUILDDIR ]; then
   rm -rf $BUILDDIR/*
@@ -127,7 +136,7 @@ mkdir -p $PKGDIR
 cd $BUILDDIR
 
 # check for installer script
-ISSFILE=$PT_REPO_PATH/packaging/win-installer/photivo-setup-win${PT_BIT}.iss
+ISSFILE=$PhotivoRepoPath/packaging/win-installer/photivo-setup-win${GccArch}.iss
 if [ ! -s $ISSFILE ]; then
   Error "$ISSFILE is missing/corrupted!"
   exit 1
@@ -137,8 +146,8 @@ fi
 
 # build Photivo
 echo "Building Photivo and ptClear ..."
-$QMAKECMD ../photivo.pro CONFIG+=WithoutGimp CONFIG-=debug && \
-make -j${MAKE_THREADS}
+$QmakeCmd ../photivo.pro CONFIG+=WithoutGimp CONFIG-=debug && \
+$MakeCmd -j${JobsForMake}
 
 if [ ! $? -eq 0 ] || [ ! -s $BUILDDIR/photivo.exe ] || [ ! -s $BUILDDIR/ptClear.exe ]
 then
@@ -166,8 +175,8 @@ if [ ! $? -eq 0 ]; then
   exit 1
 fi
 
-cp $PT_REPO_PATH/COPYING $BINDIR/License.txt && \
-ln $PT_REPO_PATH/../Changelog.txt $BINDIR
+cp $PhotivoRepoPath/COPYING $BINDIR/License.txt && \
+ln $PhotivoRepoPath/../Changelog.txt $BINDIR
 if [ ! $? -eq 0 ]; then
   Error "Copying License.txt or linking Changelog.txt failed!"
   exit 1
@@ -178,7 +187,7 @@ fi
 # test for current changelog
 while :
 do
-  PT_CHLOG_DATE=$(stat -c %y $PT_REPO_PATH/../Changelog.txt)
+  PT_CHLOG_DATE=$(stat -c %y $PhotivoRepoPath/../Changelog.txt)
   PT_CHLOG_DATE=${PT_CHLOG_DATE%% *}
   if [ "$(date +%Y-%m-%d)" == "$PT_CHLOG_DATE" ]; then
     break
@@ -186,7 +195,8 @@ do
     Error "\nChangelog not edited today, but on ${PT_CHLOG_DATE}."
     read -n 1 -p "(R)etry, (c)ontinue or (a)bort?" PT_CONT
     if [ "$PT_CONT" = "c" ] || [ "$PT_CONT" = "C" ]; then
-     break
+      printf "\n"
+      break
     elif [ "$PT_CONT" = "a" ] || [ "$PT_CONT" = "A" ]; then
       exit 1
     fi
@@ -194,18 +204,25 @@ do
 done
 
 # Create installer
-VERSTRING=$( $HGCMD log -b ${HGBRANCH} -l 1 --style ${SCRIPTDIR}/hg-revdatenum.style )
-NATIVECHLOGPATH=$( echo $REALBASEDIR/Changelog.txt | sed 's|/|\\\\|g' )
-SETUPNAME=photivo-setup-${RELEASEDATE}-win$PT_BIT
-NATIVEBINDIR=$( echo $BINDIR | sed "s|/photivo|${REALBASEDIR}|" | sed 's|/|\\\\|g' )
-NATIVEPKGDIR=$( echo $PKGDIR | sed "s|/photivo|${REALBASEDIR}|" | sed 's|/|\\\\|g' )
+VERSTRING=$( $HgCmd log -b ${HGBRANCH} -l 1 --style ${ScriptPath}/hg-revdatenum.style )
+NATIVECHLOGPATH=$( echo $RealBasePath/Changelog.txt | sed 's|/|\\\\|g' )
+SETUPNAME=photivo-setup-${RELEASEDATE}-win${GccArch}
+NATIVEBINDIR=$( echo $BINDIR | sed "s|${MsysBasePath}|${RealBasePath}|I" | sed 's|/|\\\\|g' )
+NATIVEPKGDIR=$( echo $PKGDIR | sed "s|${MsysBasePath}|${RealBasePath}|I" | sed 's|/|\\\\|g' )
 
-cat $PT_REPO_PATH/packaging/win-installer/photivo-setup-win${PT_BIT}.iss | \
+printf "\nVariables for Inno installer\n"
+printf "VERSTRING = $VERSTRING\n"
+printf "NATIVECHLOGPATH = $NATIVECHLOGPATH\n"
+printf "SETUPNAME = $SETUPNAME\n"
+printf "NATIVEBINDIR = $NATIVEBINDIR\n"
+printf "NATIVEPKGDIR = $NATIVEPKGDIR\n\n"
+
+cat $PhotivoRepoPath/packaging/win-installer/photivo-setup-win${GccArch}.iss | \
 sed "s/{{versionstring}}/${VERSTRING}/" | \
 sed "s/{{changelogfile}}/${NATIVECHLOGPATH}/" | \
 sed "s/{{outputbasename}}/${SETUPNAME}/" | \
 sed "s/{{bindir}}/${NATIVEBINDIR}/" | \
-/c/bin32/InnoSetup/ISCC /O$NATIVEPKGDIR -
+$IsscCmd /O$NATIVEPKGDIR -
 
 if [ ! $? -eq 0 ] || [ ! -s ${PKGDIR}/${SETUPNAME}.exe ]; then
   Error "Creating installer failed!"
@@ -215,11 +232,11 @@ fi
 #===============================================================================
 
 # Build troubleshooter
-echo "Building ${PT_BIT}bit troubleshooter ..."
+printf "\nBuilding ${GccArch}bit troubleshooter ...\n"
 cd $BUILDDIR
 rm -f ./photivo.exe ./Objects/ptMain.o
-$QMAKECMD ../photivo.pro "CONFIG+=WithoutGimp WithoutClear console" CONFIG-=debug && \
-make -j${MAKE_THREADS}
+$QmakeCmd ../photivo.pro "CONFIG+=WithoutGimp WithoutClear console" CONFIG-=debug && \
+$MakeCmd -j${JobsForMake}
 
 if [ ! $? -eq 0 ] || [ ! -s $BUILDDIR/photivo.exe ]
 then
@@ -228,15 +245,15 @@ then
 fi
 
 cd $TSHOOTDIR
-cp $BUILDDIR/photivo.exe ./ptConsole${PT_BIT}.exe
-cp "$PT_REPO_PATH/packaging/troubleshooter/How to use.txt" \
-   "$PT_REPO_PATH/packaging/troubleshooter/ptTroubleshoot.bat" .
+cp $BUILDDIR/photivo.exe ./ptConsole${GccArch}.exe
+cp "$PhotivoRepoPath/packaging/troubleshooter/How to use.txt" \
+   "$PhotivoRepoPath/packaging/troubleshooter/ptTroubleshoot.bat" .
 
 rm -f $PKGDIR/photivo-win3264-troubleshooter*
 'ls' -1 "How to use.txt" ptTroubleshoot.bat ptConsole32.exe ptConsole64.exe > /dev/null 2>&1
 if [ $? -eq 0 ]; then
-  $ZIPCMD a $PKGDIR/photivo-win3264-troubleshooter-${RELEASEDATE}.zip \
-            "How to use.txt" ptTroubleshoot.bat ptConsole32.exe ptConsole64.exe
+  $ZipCmd $PKGDIR/photivo-win3264-troubleshooter-${RELEASEDATE}.zip \
+          "How to use.txt" ptTroubleshoot.bat ptConsole32.exe ptConsole64.exe
   if [ ! $? -eq 0 ]; then
     Error "Creating troubleshooter archive failed!"
     exit 1
@@ -245,7 +262,8 @@ fi
 
 #===============================================================================
 
-cd $PT_REPO_PATH
+cd $PhotivoRepoPath
+echo    ""
 echo    "---------------------------------------------------------------------------"
 echo    "Final status"
 echo    "---------------------------------------------------------------------------"
@@ -256,24 +274,28 @@ FileYesNo $PKGDIR/photivo-setup-${RELEASEDATE}-win32.exe
 echo -e "Troubleshooter archive: \c"
 FileYesNo $PKGDIR/photivo-win3264-troubleshooter-${RELEASEDATE}.zip
 echo -e "\nChangeset info:"
-$HGCMD log -b ${HGBRANCH} -l 1
+$HgCmd log -b ${HGBRANCH} -l 1
 echo    "---------------------------------------------------------------------------"
 
 if [ -s $PKGDIR/photivo-setup-${RELEASEDATE}-win64.exe ] && \
    [ -s $PKGDIR/photivo-setup-${RELEASEDATE}-win32.exe ] && \
    [ -s $PKGDIR/photivo-win3264-troubleshooter-${RELEASEDATE}.zip ]
 then
-  echo -e "\nEverything looks fine. You can test and upload the release now."
-  echo    "Afterwards I can clean up automatically, i.e.:"
-  echo    "* move installers to software archive,"
-  echo -e "* delete everything else created in the build process.\n"
+  printf "\nEverything looks fine. You can test and upload the release now.\n"
+  printf "The packages are located in\n"
+  printf "$ColorGreen$PKGDIR$ColorNone\n\n"
+  
+  printf "Afterwards I can clean up automatically, i.e.:\n"
+  printf "* move installers to \"$ArchivePath\",\n"
+  printf "* delete everything else created in the build process.\n\n"
+  
   read -n 1 -p "Shall I clean up now? (y/n)" ptcleanup
 
   if [ "$ptcleanup" = "y" ] || [ "$ptcleanup" = "Y" ]; then
     Cleanup
   else
     echo -e "\nOK. The mess stays!"
-    echo -e "${COLOR_GREEN}All done.${COLOR_NONE}"
+    echo -e "${ColorGreen}All done.${ColorNone}"
   fi
 
 else
diff --git a/packaging/scripts/photivo-update-libs b/packaging/scripts/photivo-update-libs
--- a/packaging/scripts/photivo-update-libs
+++ b/packaging/scripts/photivo-update-libs
@@ -3,10 +3,10 @@
 cpDestOpts=--preserve=timestamps
 Prefix=/my
 
-if [[ "$PT_REPO_PATH" == "" ]];              then printf "PT_REPO_PATH not set!\n"     ; exit 1 ; fi
-if [[ "$PT_BINDIR"    == "" ]];              then printf "PT_BINDIR not set!\n"        ; exit 1 ; fi
-if [[ "$PT_BIT"       == "" ]];              then printf "PT_BIT not set!\n"           ; exit 1 ; fi
-if [[ ($PT_BIT != 64) && ($PT_BIT != 32) ]]; then printf "Wrong PT_BIT (${PT_BIT})!\n" ; exit 1 ; fi
+if [[ "$PhotivoRepoPath"  == "" ]];            then printf "PhotivoRepoPath not set!\n"    ; exit 1 ; fi
+if [[ "$PhotivoBuildPath" == "" ]];            then printf "PhotivoBuildPath not set!\n"   ; exit 1 ; fi
+if [[ "$GccArch"       == "" ]];               then printf "GccArch not set!\n"            ; exit 1 ; fi
+if [[ ($GccArch != 64) && ($GccArch != 32) ]]; then printf "Wrong GccArch (${GccArch})!\n" ; exit 1 ; fi
 
 Result () {
   if [[ $1 == 0 ]]; then
@@ -23,11 +23,11 @@ Result () {
 if [[ "$1" != "" ]]; then
   TheBindir="$1"
 else
-  if [ ! -d "$PT_REPO_PATH" ]; then
-    echo "Path to repository \"$PT_REPO_PATH\" not found."
+  if [ ! -d "$PhotivoBuildPath" ]; then
+    echo "Path to build folder \"$PhotivoBuildPath\" not found."
     exit 1
   fi
-  TheBindir="$PT_REPO_PATH/$PT_BINDIR"
+  TheBindir="$PhotivoBuildPath"
 fi
 
 
@@ -39,7 +39,7 @@ else
   rm -f "$TheBindir/*.dll"
 fi
 
-if [[ "$PT_BIT" == "64" ]]; then
+if [[ "$GccArch" == "64" ]]; then
   cd /mingw/qt/bin && \
   cp QtCore4.dll \
      QtGui4.dll \
@@ -60,7 +60,7 @@ if [[ "$PT_BIT" == "64" ]]; then
      zlib1.dll \
      $TheBindir $cpDestOpts
 
-elif [[ "$PT_BIT" == "32" ]]; then
+elif [[ "$GccArch" == "32" ]]; then
   cd /mingw/qt/bin && \
   cp QtCore4.dll \
      QtGui4.dll \
